name: RNAseq
channels:
- conda-forge
- bioconda
- defaults
- r
dependencies:
- bedtools=2.27.1
- bioconductor-annotate=1.56.0
- bioconductor-annotationdbi=1.40.0
- bioconductor-apeglm=1.0.3
- bioconductor-biobase=2.38.0
- bioconductor-biomart=2.34.0
- bioconductor-deseq2=1.18.1
- bioconductor-edaseq=2.12.0
- bioconductor-genomicranges=1.30.0
- bioconductor-iranges=2.12.0
- bioconductor-rtracklayer=1.38.0
- bioconductor-ruvseq=1.12.0
- bioconductor-s4vectors=0.16.0
- bowtie2=2.3.3.1
- cutadapt=1.15
- deeptools=3.1.1
- fastq-screen=0.11.3
- fastqc=0.11.6
- ipykernel=4.8.2
- kallisto=0.43.0
- multiqc=1.6a0
- pybedtools=0.7.10
- pybigwig=0.3.11
- pysam=0.14.1
- r-sleuth=0.29.0
- rsem=1.3.0
- samtools=1.3
- star=2.6.0c
- matplotlib-venn=0.11.5
- pandas=0.21.1
- papermill=0.14.2
- pypdf2
- python=3.6.3
- pyyaml=3.12
- r-ashr=2.0.5
- r-base=3.4.1
- rpy2=2.8.5
- seaborn=0.8.1
- statsmodels=0.8.0
- watermark=1.5.0
- xlrd
- xlwt
- openpyxl
- yaml=0.1.6
- numpy=1.14.2
- openjdk=8.0.121
- scikit-learn=0.19.1
- scipy=1.1.0
- notebook